packages:
  - "packages/*"
  - "example/*"
  - "site/**"
  - "jenpack/**"
  - "bench/**"
  - "preactsc/**"
  - "docs/**"
  - "my-app/**"
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sqlite3
